services:
  mongodb:
    image: mongo:7
    container_name: eduquest-mongodb
    ports:
      - "27017:27017"
    volumes:
      - eduquest_mongo_data:/data/db
    restart: unless-stopped

volumes:
  eduquest_mongo_data:
